//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebShop.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В корзину.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наличии.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Более 100 всемирно известных лейблов, включая собственную линию Fashion. А также ежедневные советы по стилю и модные новости..
        /// </summary>
        public static string BlockqouteDressFor {
            get {
                return ResourceManager.GetString("BlockqouteDressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТВОИ ЛЮБИМЫЕ БРЕНДЫ 
        ///ПОД ОДНОЙ КРЫШЕЙ.
        /// </summary>
        public static string BlockqouteDressForTitle {
            get {
                return ResourceManager.GetString("BlockqouteDressForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить сейчас.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция стильных платьев.
        /// </summary>
        public static string CarouselTitle {
            get {
                return ResourceManager.GetString("CarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашей корзине {0} тов..
        /// </summary>
        public static string CartItems {
            get {
                return ResourceManager.GetString("CartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша корзина пуста.
        /// </summary>
        public static string CartNoItems {
            get {
                return ResourceManager.GetString("CartNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to категории.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гривна - UAH.
        /// </summary>
        public static string CurrencyUAH {
            get {
                return ResourceManager.GetString("CurrencyUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доллар - USD.
        /// </summary>
        public static string CurrencyUSD {
            get {
                return ResourceManager.GetString("CurrencyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одежда для.
        /// </summary>
        public static string DressFor {
            get {
                return ResourceManager.GetString("DressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  и более &lt;b class=&apos;color-h&apos;&gt; {{{{(items|countPrice:{0}:{1}).length}}}}&lt;/b&gt;.
        /// </summary>
        public static string FilterPriceMore {
            get {
                return ResourceManager.GetString("FilterPriceMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мужчин.
        /// </summary>
        public static string ForMan {
            get {
                return ResourceManager.GetString("ForMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to женщин.
        /// </summary>
        public static string ForWoman {
            get {
                return ResourceManager.GetString("ForWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to смотреть.
        /// </summary>
        public static string GoView {
            get {
                return ResourceManager.GetString("GoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to есть.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мужское.
        /// </summary>
        public static string IsMan {
            get {
                return ResourceManager.GetString("IsMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to женское.
        /// </summary>
        public static string IsWoman {
            get {
                return ResourceManager.GetString("IsWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнии посты.
        /// </summary>
        public static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше о нас.
        /// </summary>
        public static string MoreUs {
            get {
                return ResourceManager.GetString("MoreUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые поступления.
        /// </summary>
        public static string NewGoods {
            get {
                return ResourceManager.GetString("NewGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет в наличии.
        /// </summary>
        public static string NotInStock {
            get {
                return ResourceManager.GetString("NotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары магазина.
        /// </summary>
        public static string ProductShop {
            get {
                return ResourceManager.GetString("ProductShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайные товары.
        /// </summary>
        public static string RandProd {
            get {
                return ResourceManager.GetString("RandProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать больше.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнии просмотренные товары.
        /// </summary>
        public static string RecentlyViewed {
            get {
                return ResourceManager.GetString("RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать по.
        /// </summary>
        public static string ShopBy {
            get {
                return ResourceManager.GetString("ShopBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр покупки.
        /// </summary>
        public static string ShopOpt {
            get {
                return ResourceManager.GetString("ShopOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string ToUp {
            get {
                return ResourceManager.GetString("ToUp", resourceCulture);
            }
        }
    }
}
