//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebShop.App_GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebShop.App_GlobalResources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to о нас.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to применить.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мой профиль.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В корзину.
        /// </summary>
        public static string AddToCart {
            get {
                return ResourceManager.GetString("AddToCart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to товар не был добавлен в корзину.
        /// </summary>
        public static string AddToCartError {
            get {
                return ResourceManager.GetString("AddToCartError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to товар был успешно добавлен в корзину.
        /// </summary>
        public static string AddToCartSuccess {
            get {
                return ResourceManager.GetString("AddToCartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрация.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары.
        /// </summary>
        public static string AllProducts {
            get {
                return ResourceManager.GetString("AllProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Произошла ошибка.
        /// </summary>
        public static string AnotherError {
            get {
                return ResourceManager.GetString("AnotherError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В наличии.
        /// </summary>
        public static string Availability {
            get {
                return ResourceManager.GetString("Availability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ваша корзина пуста.
        /// </summary>
        public static string BagEmpty {
            get {
                return ResourceManager.GetString("BagEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Более 100 всемирно известных лейблов, включая собственную линию Fashion. А также ежедневные советы по стилю и модные новости..
        /// </summary>
        public static string BlockqouteDressFor {
            get {
                return ResourceManager.GetString("BlockqouteDressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ТВОИ ЛЮБИМЫЕ БРЕНДЫ 
        ///ПОД ОДНОЙ КРЫШЕЙ.
        /// </summary>
        public static string BlockqouteDressForTitle {
            get {
                return ResourceManager.GetString("BlockqouteDressForTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Купить сейчас.
        /// </summary>
        public static string BuyNow {
            get {
                return ResourceManager.GetString("BuyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ваш заказ принят, в ближайшее время с вами свяжется наш сотрудник магазина!.
        /// </summary>
        public static string BuySuccess {
            get {
                return ResourceManager.GetString("BuySuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коллекция стильных платьев.
        /// </summary>
        public static string CarouselTitle {
            get {
                return ResourceManager.GetString("CarouselTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Корзина.
        /// </summary>
        public static string Cart {
            get {
                return ResourceManager.GetString("Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В вашей корзине {0} тов..
        /// </summary>
        public static string CartItems {
            get {
                return ResourceManager.GetString("CartItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваша корзина пуста.
        /// </summary>
        public static string CartNoItems {
            get {
                return ResourceManager.GetString("CartNoItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to категории.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to оформить заказ.
        /// </summary>
        public static string Checkout {
            get {
                return ResourceManager.GetString("Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to очистить фильтр.
        /// </summary>
        public static string ClearFilter {
            get {
                return ResourceManager.GetString("ClearFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to цвет.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтверждение email.
        /// </summary>
        public static string ConfEmailPage {
            get {
                return ResourceManager.GetString("ConfEmailPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ваш email успешно подтвержден.
        /// </summary>
        public static string ConfEmailSucces {
            get {
                return ResourceManager.GetString("ConfEmailSucces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подтверждение пароля.
        /// </summary>
        public static string ConfirmPswd {
            get {
                return ResourceManager.GetString("ConfirmPswd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароли не совпадают.
        /// </summary>
        public static string ConfirmPswdInValid {
            get {
                return ResourceManager.GetString("ConfirmPswdInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to наши контакты.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Валюта.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Гривна - UAH.
        /// </summary>
        public static string CurrencyUAH {
            get {
                return ResourceManager.GetString("CurrencyUAH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Доллар - USD.
        /// </summary>
        public static string CurrencyUSD {
            get {
                return ResourceManager.GetString("CurrencyUSD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ru.
        /// </summary>
        public static string CurrentLang {
            get {
                return ResourceManager.GetString("CurrentLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to данные не коректны.
        /// </summary>
        public static string DataError {
            get {
                return ResourceManager.GetString("DataError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to дата покупки.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to описание.
        /// </summary>
        public static string Desc {
            get {
                return ResourceManager.GetString("Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to На сайте магазина, вы сможете подобрать одежду на любой вкус, в нем представлены десятки тысяч товаров. Fashion обновляет свой ассортимент каждую среду (товаром который вернули). Помимо своей марки мужской, женской одежды, сумок, и аксессуаров в интернет-магазине собраны известные Британские бренды, а также самые популярные бренды Европы и США: Esprit, G-Star, Levi&apos;s, Ray-Ban, Diesel, Adidas и другие. Ассортимент товара рассчитан в основном на молодых людей в возрасте от 16 до 35 лет. Помимо обуви, одежды,  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Descriptions {
            get {
                return ResourceManager.GetString("Descriptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Детали.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидка.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы хотите удалить текущий продукт из корзины?.
        /// </summary>
        public static string DoYouWantRemove {
            get {
                return ResourceManager.GetString("DoYouWantRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to одежда для.
        /// </summary>
        public static string DressFor {
            get {
                return ResourceManager.GetString("DressFor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to указанный вами email уже существует.
        /// </summary>
        public static string EmailDuplicat {
            get {
                return ResourceManager.GetString("EmailDuplicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to введите верно email.
        /// </summary>
        public static string EmailInValid {
            get {
                return ResourceManager.GetString("EmailInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Английский.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to эксклюзив.
        /// </summary>
        public static string Exclusive {
            get {
                return ResourceManager.GetString("Exclusive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to страница подтврждения внешней авторизации.
        /// </summary>
        public static string ExtLgConf {
            get {
                return ResourceManager.GetString("ExtLgConf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to быстрый заказ.
        /// </summary>
        public static string FastCheckout {
            get {
                return ResourceManager.GetString("FastCheckout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вам потребуется указать
        ///только имя и номер телефона.
        /// </summary>
        public static string FastOrderTool {
            get {
                return ResourceManager.GetString("FastOrderTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to фильтр.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  и более &lt;b class=&apos;color-h&apos;&gt; {{{{(items|countPrice:{0}:{1}).length}}}}&lt;/b&gt;.
        /// </summary>
        public static string FilterPriceMore {
            get {
                return ResourceManager.GetString("FilterPriceMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Женская обувь предназначенная для элегантной одежды, работы, и отдыха.
        /// </summary>
        public static string FootWearW {
            get {
                return ResourceManager.GetString("FootWearW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мужчин.
        /// </summary>
        public static string ForMan {
            get {
                return ResourceManager.GetString("ForMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to женщин.
        /// </summary>
        public static string ForWoman {
            get {
                return ResourceManager.GetString("ForWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Полноценное оформление заказа.
        /// </summary>
        public static string FullOrderTool {
            get {
                return ResourceManager.GetString("FullOrderTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to смотреть.
        /// </summary>
        public static string GoView {
            get {
                return ResourceManager.GetString("GoView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to история.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главная.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to информация.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to есть.
        /// </summary>
        public static string InStock {
            get {
                return ResourceManager.GetString("InStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to неправильный логин или пароль,электронный адрес не подтвержден.
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to мужское.
        /// </summary>
        public static string IsMan {
            get {
                return ResourceManager.GetString("IsMan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to женское.
        /// </summary>
        public static string IsWoman {
            get {
                return ResourceManager.GetString("IsWoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнии посты.
        /// </summary>
        public static string LatestPosts {
            get {
                return ResourceManager.GetString("LatestPosts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Войти.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выйти.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to главная.
        /// </summary>
        public static string Main {
            get {
                return ResourceManager.GetString("Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Больше о нас.
        /// </summary>
        public static string MoreUs {
            get {
                return ResourceManager.GetString("MoreUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имя.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to указанное вами имя уже существует.
        /// </summary>
        public static string NameDuplicat {
            get {
                return ResourceManager.GetString("NameDuplicat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to имя пользователя должно содержать от 2 и до 20 латинских символов, первый символ должен быть буквой.
        /// </summary>
        public static string NameInValid {
            get {
                return ResourceManager.GetString("NameInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новые поступления.
        /// </summary>
        public static string NewGoods {
            get {
                return ResourceManager.GetString("NewGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to не достаточно товара {0}, выберите количество не более {1}.
        /// </summary>
        public static string NoEnoughtGoods {
            get {
                return ResourceManager.GetString("NoEnoughtGoods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to нет в наличии.
        /// </summary>
        public static string NotInStock {
            get {
                return ResourceManager.GetString("NotInStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to применить.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to пароль должен содержать от 6 до 20 латинских символов  начинаться с буквы.
        /// </summary>
        public static string PaswdInValid {
            get {
                return ResourceManager.GetString("PaswdInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;b&gt;СПОСОБЫ ОПЛАТЫ:&lt;/b&gt;&lt;br/&gt;
        ///Предоплата банковской картой или через PayPal.
        ///(Если вы хотите оплатить покупки при помощи PayPal, пожалуйста,
        ///выберите валюту отличную от гривны).
        /// </summary>
        public static string PayMentMeth {
            get {
                return ResourceManager.GetString("PayMentMeth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to телефонный номер не валиден (номер должен состоять от 10 до 15 цифр).
        /// </summary>
        public static string PhoneInValid {
            get {
                return ResourceManager.GetString("PhoneInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to телефонный номер.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Товары магазина.
        /// </summary>
        public static string ProductShop {
            get {
                return ResourceManager.GetString("ProductShop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кол-во.
        /// </summary>
        public static string Qty {
            get {
                return ResourceManager.GetString("Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Случайные товары.
        /// </summary>
        public static string RandProd {
            get {
                return ResourceManager.GetString("RandProd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Читать больше.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Последнии просмотренные товары.
        /// </summary>
        public static string RecentlyViewed {
            get {
                return ResourceManager.GetString("RecentlyViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to на ваш электронный адрес было отправлено письмо, перейдите по ссылке указанной в нем и подтвердите регистрацию.
        /// </summary>
        public static string RegConfirmMessage {
            get {
                return ResourceManager.GetString("RegConfirmMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Регистрация.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запомнить меня?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Русский.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string s {
            get {
                return ResourceManager.GetString("s", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Скидки.
        /// </summary>
        public static string Sale {
            get {
                return ResourceManager.GetString("Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сохранить.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Фильтр покупки.
        /// </summary>
        public static string ShopOpt {
            get {
                return ResourceManager.GetString("ShopOpt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to размер.
        /// </summary>
        public static string Size {
            get {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to аккаунты в социальных сетях.
        /// </summary>
        public static string SocialAccount {
            get {
                return ResourceManager.GetString("SocialAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to сортировать по.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Новинки.
        /// </summary>
        public static string SortByNew {
            get {
                return ResourceManager.GetString("SortByNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбрать.
        /// </summary>
        public static string SortByNone {
            get {
                return ResourceManager.GetString("SortByNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена по возрастанию.
        /// </summary>
        public static string SortByPriceAsc {
            get {
                return ResourceManager.GetString("SortByPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Цена по убыванию.
        /// </summary>
        public static string SortByPriceDesc {
            get {
                return ResourceManager.GetString("SortByPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to подкатегории.
        /// </summary>
        public static string SubCategory {
            get {
                return ResourceManager.GetString("SubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to выполнено успешно.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сумма .
        /// </summary>
        public static string Summa {
            get {
                return ResourceManager.GetString("Summa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to общая стоимость.
        /// </summary>
        public static string TotalCoast {
            get {
                return ResourceManager.GetString("TotalCoast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to до.
        /// </summary>
        public static string ToUp {
            get {
                return ResourceManager.GetString("ToUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to информация.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to кабинет пользователя.
        /// </summary>
        public static string UserRoom {
            get {
                return ResourceManager.GetString("UserRoom", resourceCulture);
            }
        }
    }
}
