// <auto-generated />
namespace WebShop.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SaleAddUserName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SaleAddUserName));
        
        string IMigrationMetadata.Id
        {
            get { return "201510301728538_SaleAddUserName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
